services:
  db:
    image: mysql:8.0.37
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - prop-invest-find-network

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/prop-invest-find:cached
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
    networks:
      - prop-invest-find-network

volumes:
  bundle:

networks:
  prop-invest-find-network:
    driver: bridge